#!/usr/bin/env ruby
# frozen_string_literal: true

# This is a replacement for the bin/vite binstub for integration
# with bundlebun.
# We need to patch the binstub, otherwise there is no way to force
# ruby-vite that is being run via `bin/vite` to use bundlebun.
#
# The code below is the code for the original vite-ruby binstub, with
# the bundlebun initializer run injected.
#
# If you had an original `vite` binstub at this place, it should
# be at `vite-backup`.

ENV['RAILS_ENV'] ||= ENV['RACK_ENV']

require 'bundler/setup'
require 'vite_ruby'
require 'bundlebun'

cli = ViteRuby::CLI
cli.require_framework_libraries
Bundlebun::Integrations::ViteRuby.bun!

Dry::CLI.new(cli).call
