module Bundlebun
  class Runner
    BINSTUB_PATH: String
    RELATIVE_DIRECTORY: String

    # Replaces the current Ruby process with Bun. Never returns.
    def self.exec: (String | Array[String] arguments) -> bot

    # Replaces the current Ruby process with Bun. Alias for .exec. Never returns.
    def self.call: (String | Array[String] arguments) -> bot

    # Runs Bun as a subprocess and returns control to Ruby.
    def self.system: (String | Array[String] arguments) -> bool?

    def self.binstub_path: () -> String
    def self.full_binstub_path: () -> String
    def self.relative_directory: () -> String
    def self.full_directory: () -> String
    def self.binary_path: () -> String
    def self.binary_path_exist?: () -> bool
    def self.binstub_or_binary_path: () -> String
    def self.binstub_exist?: () -> bool

    def initialize: (?String | Array[String] arguments) -> void

    # Replaces the current Ruby process with Bun. Never returns.
    def exec: () -> bot

    # Replaces the current Ruby process with Bun. Alias for #exec. Never returns.
    def call: () -> bot

    # Runs Bun as a subprocess and returns control to Ruby.
    def system: () -> bool?
  end
end
