#!/usr/bin/env ruby
# frozen_string_literal: true

# Install the gem first, then create a binstub.
#
# Add to your Gemfile:
#
#   gem 'bundlebun'
#
# Then:
#
#   bundle install
#   rake bun:install
#
# And then:
#
#   bin/bun ...
#
# If you're seeing this in your `bin/` directory and you're
# no longer using bundlebun, it should be safe to delete.
begin
  require 'bundler/setup'
rescue LoadError
  # Continue without bundler if not available
end
require 'bundlebun'

Bundlebun::Runner.call(ARGV)
