module Bundlebun
  module Integrations
    module Jsbundling
      def self.bun!: () -> void

      module Tasks
        def install_command: () -> String
        def build_command: () -> String
      end
    end
  end
end
