name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.3.6"
          - "3.2.6"
          - "3.4.1"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: latest
        env:
          BUNDLE_FROZEN: "false"
      - name: Download the bun executable for integration tests
        run: bundle exec rake bundlebun:download
      - name: Run RSpec
        run: bundle exec rake
